import type { Metadata } from 'next';
import { QueryProvider, ThemeProvider } from '@/app/providers';
import { nanumSquare, nanumSquareRound, sourceCodePro } from '@/shared/config';
import { cn } from '@/shared/lib';
import { Layout } from '@/widgets/layout';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="scroll-smooth" suppressHydrationWarning>
      <body
        className={cn(
          nanumSquare.variable,
          nanumSquareRound.variable,
          sourceCodePro.variable,
          'antialiased',
        )}
      >
        <QueryProvider>
          <ThemeProvider>
            <Layout>{children}</Layout>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
